line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "C"]
ignore = ["E501"]

[lint.pylint]
max-args = 10

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
